---
- name: ensure git installed
  package:
    name: git
    state: present

- name: set git user name and email
  become: yes
  become_user: '{{ user.username }}'
  git_user:
    name: '{{ user.git_user_name | default(omit) }}'
    email: '{{ user.git_user_email | default(omit) }}'
    force: '{{ user.git_user_force | default(omit) }}'
  with_items: '{{ users | default([]) }}'
  loop_control:
    loop_var: user
    label: '{{ user.username }}'
